v1.37.0 Update api-updates.rss
upvestco/documentation_assets pull request #4
Opened 2024-10-01 12:29 UTC by lengocduong1

2024-10-01 12:33 UTC, upmkrasiukov commented on feed/api-updates.rss
>      <pubDate>Thu, 26 Sep 2024 13:00:00 +0000</pubDate>
needs to be updated too

2024-10-01 12:34 UTC, upmkrasiukov commented on feed/api-updates.rss
> +    <title>v1.37.0 Corporate action notifications</title>
need +1 indentation

2024-10-01 12:54 UTC, upmkrasiukov requested changes

2024-10-01 12:54 UTC, upmkrasiukov commented on feed/api-updates.rss
> +      <description>Operation models: TOL, BYOL, OMNIBUS\\nChanges: ...</description>
Would you like to write a short summary of the changes?
Also for the new line use `&lt;br/&gt;` (updated the guide)

2024-10-01 12:55 UTC, upmkrasiukov commented on feed/api-updates.rss
> +    <pubDate>Tue, 01 Oct 2024 13:00:00 +0000</pubDate>
should be similar to item's pubDate to pass validation

2024-10-02 08:18 UTC, forik submitted a review, later dismissed

2024-10-02 08:26 UTC, upmkrasiukov approved these changes

2024-10-02 08:27 UTC, merged